'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")>  _
Partial Friend NotInheritable Class UserData
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As UserData = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New UserData()),UserData)
    
    Public Shared ReadOnly Property [Default]() As UserData
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Tqco")>  _
    Public Property UserString() As String
        Get
            Return CType(Me("UserString"),String)
        End Get
        Set
            Me("UserString") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("String")>  _
    Public Property URI() As String
        Get
            Return CType(Me("URI"),String)
        End Get
        Set
            Me("URI") = value
        End Set
    End Property
End Class
